version: '3.8'

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - redis
      - db
    environment:
      APP_URL: "http://localhost:3000"
      APP_SECRET: "84ee6265db96f6c2ee4f8fd1f4b00b25dd8c2981d0e2675b44bdc6c66ad6711b"
      DATABASE_URL: "postgresql://postgres:1234@db:5432/docmost"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  postgres_data:
  redis_data:

  

